### ISSUE TITLE
Pre-commit hook fails - always

### ISSUE THREAD

**Issue by rakeshtembhurne** [pesto-students/batch-8-CODERHOOD#36]
There is an issue with the pre-commit hook, it is failing almost always. It has something to do with the wrong version of 'eslint' package. 

Refer: #3 

![image](https://user-images.githubusercontent.com/1090611/61140235-b5254f80-a4e8-11e9-8188-8416fa31bd20.png)

**Comment by sourabhmodi20051** [comment]
Fixed by adding react dependency in root folder package.json. Shall we proceed with this change?
